import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import {Noto_Serif_Tamil} from 'next/font/google'
import {} from 'next/font/google'
//NotoSerifTamilSlanted

import "./globals.css";

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
})

const notoSerifTamil = Noto_Serif_Tamil({
  subsets: ['latin'],
  display: 'swap',
})
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className}  ${notoSerifTamil.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
