import type { Metadata } from "next";
import { notoSerifTamil, openSans, poppins } from "../Fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${openSans.variable}
          ${poppins.variable}
          ${notoSerifTamil.variable}
          font-sans
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
